"""
OACP (OpenNewt Agent Communication Protocol) v0.1

通信协议库 - 所有 Agent 消息传递的标准格式
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
import json


class MessageType(Enum):
    """消息类型枚举"""
    SIGNAL = "SIGNAL"  # 损伤信号：Soma → Plasticus
    BLUEPRINT = "BLUEPRINT"  # 修复蓝图：Plasticus → Effector
    EXECUTION_REPORT = "EXECUTION_REPORT"  # 执行报告：Effector → Plasticus + Mnemosyne
    QUERY = "QUERY"  # 查询历史：任意 → Mnemosyne
    HUMAN_ESCALATION = "HUMAN_ESCALATION"  # 人工干预：任意 → 人类
    TICK = "TICK"  # 夜间整理：Mnemosyne → All


class Priority(Enum):
    """优先级枚举"""
    P0 = "P0"  # 最高优先级（威胁本金安全、系统崩溃）
    P1 = "P1"  # 高优先级（影响策略执行、数据异常）
    P2 = "P2"  # 中优先级（架构改进、性能优化）


class DamageType(Enum):
    """损伤类型枚举"""
    LATENCY_ANOMALY = "延迟异常"  # API 响应 > 500ms
    RESOURCE_LEAK = "资源泄漏"  # 内存/CPU 持续增长
    BEHAVIOR_DRIFT = "行为漂移"  # 测试通过率下降
    DEPENDENCY_DECAY = "依赖腐化"  # 安全漏洞、过期依赖
    CODE_DECAY = "代码腐化"  # 复杂度超标


@dataclass
class OACPMessage:
    """OACP 消息基类"""
    type: MessageType
    source: str
    target: str
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")
    payload: Dict[str, Any] = field(default_factory=dict)
    message_id: Optional[str] = None
    
    def to_json(self) -> str:
        """序列化为 JSON"""
        return json.dumps({
            "type": self.type.value,
            "source": self.source,
            "target": self.target,
            "timestamp": self.timestamp,
            "payload": self.payload,
            "message_id": self.message_id
        }, ensure_ascii=False, indent=2)
    
    @classmethod
    def from_json(cls, json_str: str) -> 'OACPMessage':
        """从 JSON 反序列化"""
        data = json.loads(json_str)
        return cls(
            type=MessageType(data["type"]),
            source=data["source"],
            target=data["target"],
            timestamp=data["timestamp"],
            payload=data["payload"],
            message_id=data.get("message_id")
        )
    
    def to_github_issue_title(self) -> str:
        """生成 GitHub Issue 标题"""
        return f"[OACP] {self.type.value} - {self.source} → {self.target}"
    
    def to_github_issue_body(self) -> str:
        """生成 GitHub Issue 内容"""
        return f"""```json
{self.to_json()}
```

---
*Generated by Axonewt Neural Plasticity Engine*
*Timestamp: {self.timestamp}*
"""


@dataclass
class SignalMessage(OACPMessage):
    """损伤信号消息（Soma → Plasticus）"""
    type: MessageType = field(default=MessageType.SIGNAL, init=False)
    
    @classmethod
    def create(
        cls,
        damage_type: DamageType,
        severity: Priority,
        location: str,
        symptoms: List[str],
        health_score: float,
        context: Optional[Dict[str, Any]] = None
    ) -> 'SignalMessage':
        """创建损伤信号消息"""
        return cls(
            source="Soma-Dev",
            target="Plasticus-Dev",
            payload={
                "damage_type": damage_type.value,
                "severity": severity.value,
                "location": location,
                "symptoms": symptoms,
                "health_score": health_score,
                "context": context or {}
            }
        )


@dataclass
class BlueprintMessage(OACPMessage):
    """修复蓝图消息（Plasticus → Effector）"""
    type: MessageType = field(default=MessageType.BLUEPRINT, init=False)
    
    @classmethod
    def create(
        cls,
        plan_id: str,
        strategy: str,
        steps: List[Dict[str, Any]],
        estimated_downtime: str,
        success_rate_prediction: float,
        rollback_plan: str
    ) -> 'BlueprintMessage':
        """创建修复蓝图消息"""
        return cls(
            source="Plasticus-Dev",
            target="Effector-Dev",
            payload={
                "plan_id": plan_id,
                "strategy": strategy,
                "steps": steps,
                "estimated_downtime": estimated_downtime,
                "success_rate_prediction": success_rate_prediction,
                "rollback_plan": rollback_plan
            }
        )


@dataclass
class ExecutionReportMessage(OACPMessage):
    """执行报告消息（Effector → Plasticus + Mnemosyne）"""
    type: MessageType = field(default=MessageType.EXECUTION_REPORT, init=False)
    
    @classmethod
    def create(
        cls,
        plan_id: str,
        status: str,  # "success" | "partial_success" | "failed" | "rolled_back"
        steps_completed: int,
        steps_total: int,
        errors: Optional[List[str]] = None,
        health_after: Optional[float] = None
    ) -> 'ExecutionReportMessage':
        """创建执行报告消息"""
        return cls(
            source="Effector-Dev",
            target="Plasticus-Dev",  # 也会发送给 Mnemosyne
            payload={
                "plan_id": plan_id,
                "status": status,
                "steps_completed": steps_completed,
                "steps_total": steps_total,
                "errors": errors or [],
                "health_after": health_after
            }
        )


@dataclass
class QueryMessage(OACPMessage):
    """查询历史消息（任意 → Mnemosyne）"""
    type: MessageType = field(default=MessageType.QUERY, init=False)
    
    @classmethod
    def create(
        cls,
        query_type: str,  # "similar_cases" | "health_trend" | "agent_status"
        query_params: Dict[str, Any],
        source_agent: str
    ) -> 'QueryMessage':
        """创建查询消息"""
        return cls(
            source=source_agent,
            target="Mnemosyne-Dev",
            payload={
                "query_type": query_type,
                "query_params": query_params
            }
        )


@dataclass
class HumanEscalationMessage(OACPMessage):
    """人工干预消息（任意 → 人类）"""
    type: MessageType = field(default=MessageType.HUMAN_ESCALATION, init=False)
    
    @classmethod
    def create(
        cls,
        reason: str,
        context: Dict[str, Any],
        source_agent: str,
        urgency: Priority
    ) -> 'HumanEscalationMessage':
        """创建人工干预消息"""
        return cls(
            source=source_agent,
            target="Human",
            payload={
                "reason": reason,
                "context": context,
                "urgency": urgency.value
            }
        )


@dataclass
class TickMessage(OACPMessage):
    """夜间整理消息（Mnemosyne → All）"""
    type: MessageType = field(default=MessageType.TICK, init=False)
    
    @classmethod
    def create(
        cls,
        tick_type: str,  # "nightly_cleanup" | "health_check" | "pattern_mining"
        tasks: List[str]
    ) -> 'TickMessage':
        """创建夜间整理消息"""
        return cls(
            source="Mnemosyne-Dev",
            target="All",
            payload={
                "tick_type": tick_type,
                "tasks": tasks
            }
        )


# 示例使用
if __name__ == "__main__":
    # 创建一个损伤信号
    signal = SignalMessage.create(
        damage_type=DamageType.RESOURCE_LEAK,
        severity=Priority.P0,
        location="src/api/handler.rs:142",
        symptoms=["内存占用持续增长", "未释放的数据库连接"],
        health_score=0.62,
        context={
            "last_24h_events": [],
            "related_components": ["数据库连接池", "缓存层"]
        }
    )
    
    print("GitHub Issue Title:")
    print(signal.to_github_issue_title())
    print("\nGitHub Issue Body:")
    print(signal.to_github_issue_body())
